# Generated by Django 4.1 on 2022-08-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adress',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
