# Generated by Django 4.1 on 2022-08-29 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_post',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
