# Generated by Django 4.1 on 2022-09-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_time_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Science', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='football-team'),
        ),
    ]
