# Generated by Django 4.1 on 2022-08-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=255)),
                ('visaun', models.TextField(max_length=455)),
                ('misaun', models.TextField(max_length=455)),
                ('service', models.TextField(max_length=255)),
            ],
        ),
    ]
